#!/bin/sh

cat /LICENSE

toBool() {
    echo $(echo $1 | awk '{print (tolower($0)~"(^yes$)|(^true$)|(^[-+]?[0-9]*[1-9][0-9]*$)")?"true":"false"}')
}

SERVER_MODE=$(toBool ${SSH_SERVER})
CLIENT_MODE=$(toBool ${SSH_CLIENT})

if [[ "${SERVER_MODE}" == "true" ]]; then
    echo Configuring Server

    # Allow binding to ports<1024
    setcap CAP_NET_BIND_SERVICE=+eip /usr/sbin/sshd

    adduser -D ${SSH_SERVER_USER}
    passwd -u ${SSH_SERVER_USER}

    install -o root -g root -m 400 -t /etc/ssh /input/server/*
    install -o root -g root -m 400 -Dt /etc/ssh/sshd_config.d /input/server/sshd_config.d/*

    echo Include '/etc/ssh/sshd_config.d/*.conf' >> /etc/ssh/sshd_config
    echo DenyUsers ${SSH_CLIENT_USER} root >> /etc/ssh/sshd_config.d/client_deny.conf

    if [[ -f /input/server/authorized_keys ]]; then
        install -o ${SSH_SERVER_USER} -g ${SSH_SERVER_USER} -m 400 -D -t /home/${SSH_SERVER_USER}/.ssh/ /input/server/authorized_keys
    fi

    ssh-keygen -A

    rm /etc/sv/server/down
else
    echo Server disabled
fi

if [[ "${CLIENT_MODE}" == "true" ]]; then
    echo Configuring Client

    # Allow binding to ports<1024
    setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/ssh

    adduser -D ${SSH_CLIENT_USER}
    passwd -u ${SSH_CLIENT_USER}

    install -o root -g root -m 444 -Dt /etc/ssh /input/client/*
    install -o root -g root -m 444 -Dt /etc/ssh/ssh_config.d /input/client/ssh_config.d/*
    install -o ${SSH_CLIENT_USER} -g ${SSH_CLIENT_USER} -m 400 -Dt /home/${SSH_CLIENT_USER}/.ssh /input/client/user/*

    echo Include '/etc/ssh/ssh_config.d/*.conf' >> /etc/ssh/ssh_config

    rm /etc/sv/client/down
else
    echo Client disabled
fi
